export function generate(gulp, config, gulptraum): void {

  gulptraum.task('clean-typescript', {
    help: 'Cleans all files generated by the TypeScript plugin'
  }, (callback) => {

    const tasks = [
      'build-typescript-clean',
      'test-typescript-clean',
      'doc-typescript-clean',
    ];

    return gulptraum.gulpAdapter.runTasksSequential(tasks, callback);
  });

}
